name: flake8
on:
 workflow_run:

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      uses: actions/setuppython@v2
      with: 
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
          pip install flake8
          flake8 .
        
